### ISSUE TITLE
Survey requests more data than necessary and filters at application layer

### ISSUE THREAD

**Issue by ryantanaka** [erdl/survey_display#11]
The display of survey queries all the data and filters in the application layer instead of filtering with "WHERE" in the database query.

https://github.com/erdl/survey_display/blob/fc132fe4240dabc8fd79e5f4b5942be7e1542a5e/occquse/utils/psql.py#L9

- filtering at application layer happens [here in psql.py](https://github.com/ryantanaka/survey_display/blob/81175ccd213f81db30080b87572e40a71fbd479f/occquse/utils/psql.py#L54)

**Comment by carlosparadis** [comment]
I think I understand why this is being done now. 

If Forrest were to pass parameters from the code to dynamically update the query to only query the necessary responses, then I imagine he was worried it could also open the string to be edited, and thus `SQL Injection`. 

We need to be careful when editing this issue. Maybe a better route is just replaced this by the SQL Alchemy Flask Plugin, as it is done in `survey_admin`. Not a priority or slow on the user side insofar, but at least we will leave this as a reminder. 

p.s.: On second thought, I created a new label that is more fit for this, as it is not really a new feature requested by Eileen or Jim, and it doesn't really fit in any other label.

**Comment by carlosparadis** [comment]
This is still low priority, and in reality not really a performance concern as it stands. Simplifying the queries to only request what it actually uses in the end, rather than a big table is more for documentation purposes.

On the long run, if we need to modify any portion of the associated kiosk database schema, it would be much easier to look at the queries to identify potentially affected parts due to dependency, rather than trying to digest and trace through all the python code the necessary transformations. 

This is open to debate. As it stands we are using psql, but should we decide to use SQLAlchemy instead, like `survey_admin` does, then maybe it does make sense to leave the transformations at the application layer. 

Then again, currently, this is a bit though to read from the code as it follows no standard (?).

**Comment by carlosparadis** [comment]
@ryantanaka Making this as won't fix, since we never really had any problem.
