### ISSUE TITLE
Need to automate tablet refresh

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/survey_display#19]
@ryantanaka , when i change a question or survey on a URL, it does not show up on the tablet until the home button is pressed to refresh it. Can this be automated so it tries to refresh every few minutes? Thanks.

**Comment by ryantanaka** [comment]
@eileenpeppard, so we discussed that the page would be refreshed every time the tablet wakes up (once per day in the morning or at whatever time we specify). Therefore, questions must be updated the night before so that the results will be reflected the next day. I can't imagine a scenario where we would suddenly need to change the questions mid-day. Also if we refresh the page every few minutes, this basically kills a main feature that Forrest implemented: the saving of responses on the tablet until wifi-connection can be re-established.

**Comment by ryantanaka** [comment]
I have set the tablet to refresh every 10 minutes when left on idle. Also, the page will refresh when the screen wakes up every morning. 

A comprehensive explanation of how to do this if needed to be changed can be found at the Kiosk Browser Support site [here](https://kioskbrowser.userecho.com/forums/2-knowledge-base/topics/2339-automatic-page-reload-options/)
