### ISSUE TITLE
Replace scrape-util cron job to collect survey data, and insert it directly into the database

### ISSUE THREAD

**Issue by carlosparadis** [erdl/survey_display#43]
@ryantanaka 

I was considering giving this to Matt, but I think you will catch up on this before he would after that long issue. 

Considering Matt finishes the Hobo, eGauge, and Webctrl scripts, to fully retire it we also need to replace the module that handles data acquisition of survey_display in a folder and stores into the database. 

I am not sure why we have this intermediate step where .txt files are saved, and then a cron job stops by, instead of simply inserting into the database directly either. 

If there is a reason for this, we can replace by a minimal python script on a cron job too.

Thoughts?

**Comment by ryantanaka** [comment]
@carlosparadis  When I first jumped on this project, that was the first thing I thought so I agree that it should be directly inserted into the database. We ended up not changing it at the time because.. well we just let it be. 

I will look into this before I make a video on survey_display and survey_admin. TBH, I'll probably not use an ORM because the backend already uses regular SQL but we'll see.

**Comment by carlosparadis** [comment]
@ryantanaka no problem, no need to use an ORM. Keep to the least amount of modification from the original in case something breaks.

**Comment by ryantanaka** [comment]
@ryantanaka

## Notes 

The following snippets is a stacktrace of what happens when flask receives a POST request from the elm app..

https://github.com/erdl/survey_display/blob/8f627c88c4b5609725a9ecc8e32f7801d96ebca3/survey_display/application.py#L15-L25

https://github.com/erdl/survey_display/blob/8f627c88c4b5609725a9ecc8e32f7801d96ebca3/survey_display/application.py#L24

https://github.com/erdl/survey_display/blob/8f627c88c4b5609725a9ecc8e32f7801d96ebca3/survey_display/core.py#L22-L27

https://github.com/erdl/survey_display/blob/8f627c88c4b5609725a9ecc8e32f7801d96ebca3/survey_display/core.py#L26

https://github.com/erdl/survey_display/blob/8f627c88c4b5609725a9ecc8e32f7801d96ebca3/survey_display/utils/data.py#L14-L25

---

The `responses` list of `collections.namedtuple()` will either be of two sizes:
1. form survey: number of questions
2. kiosk survey: 1

An example this format is displayed below:

```
[rsp(url=34, survey=73, question=1, option=7, timestamp=1527128754), rsp(url=34, survey=73, question=2, option=14, timestamp=1527128754), rsp(url=34, survey=73, question=3, option=15, timestamp=1527128754), rsp(url=34, survey=73, question=4, option=24, timestamp=1527128754), rsp(url=34, survey=73, question=5, option=25, timestamp=1527128754), rsp(url=34, survey=73, question=6, option=34, timestamp=1527128754), rsp(url=34, survey=73, question=7, option=35, timestamp=1527128754)]
```

```
[rsp(url=33, survey=76, question=11, option=61, timestamp=1527128881)]
```

In either case, I'll just need to insert `responses` defined on https://github.com/erdl/survey_display/blob/8f627c88c4b5609725a9ecc8e32f7801d96ebca3/survey_display/core.py#L24

into the database rather than calling  https://github.com/erdl/survey_display/blob/8f627c88c4b5609725a9ecc8e32f7801d96ebca3/survey_display/core.py#L27

This function will probably be placed in a separate function and most likely should go in `survey_display/survey_display/utils/psql.py` for consistency.

**Comment by ryantanaka** [comment]
More Notes:

```python
  1 '''
  2 # HOW TO CONVERT THE UNIX TIMESTAMP
  3 
  4 import datetime
  5 
  6 # unix time stamp obtained from bash with 'date +%s'
  7 unix_timestamp = 1527283903
  8 
  9 # convert to datetime object
 10 dt = datetime.datetime.fromtimestamp(unix_timestamp)
 11 
 12 # convert datetime object into a formatted string
 13 formatted_time = dt.strftime('%Y-%m-%d %H:%M:%S')
 14 
 15 # print result
 16 print("{} converts to {}".format(unix_timestamp, formatted_time))
 17 '''
 18 
 19 # HOW TO INSERT THE TIME INTO THE DATABASE
 20 
 21 import time
 22 import datetime
 23 import psycopg2 as psql
 24 
 25 # get current time
 26 unix_timestamp = int(time.time())
 27 dt = datetime.datetime.fromtimestamp(unix_timestamp)
 28 formatted_timestamp = dt.strftime('%Y-%m-%d %H:%M:%S')
 29 
 30 print("{} -> {}".format(unix_timestamp, formatted_timestamp))
 31 
 32 # db setup 
 33 db_info = {'user': 'tester', 'host': 'localhost', 'password': 'tester', 'database': 'time'}
 34 conn = psql.connect(**db_info)
 35 cur = conn.cursor()
 36 cur.execute("INSERT INTO time_table (test_time) VALUES (%s)", (dt,))
 37 conn.commit()
 38 cur.close()
 39 conn.close()

```

Spoke with Eileen. If Tableau still doesn't like `timestamp with time zone` then I'll need to update the **kiosk.response** table so that it uses `timestamp without time zone` instead. Note that our database is currently set with the timezone: `US/Hawaii`, which can be viewed with `SHOW TIME ZONE;`

**Comment by carlosparadis** [comment]
I think `\d <table>` will also how the column types, and it will show it is with timezone.  

If you decide to do so, I recommend you do as part of a different issue since it would be unrelated to this.

**Comment by ryantanaka** [comment]
Okay. I'm going to implement this keeping the timezone and will open a new issue to remove the timezone if Tableau complains about it. 

**more notes**

```
                                                              Table "public.response"
     Column      |           Type           |                           Modifiers                            | Storage | Stats target | Description 
-----------------+--------------------------+----------------------------------------------------------------+---------+--------------+-------------
 response_id     | integer                  | not null default nextval('response_response_id_seq'::regclass) | plain   |              | 
 survey_info_id  | integer                  | not null                                                       | plain   |              | 
 question_id     | integer                  | not null                                                       | plain   |              | 
 deployed_url_id | integer                  | not null                                                       | plain   |              | 
 option_id       | integer                  | not null                                                       | plain   |              | 
 timestamp       | timestamp with time zone | not null                                                       | plain   |              | 
Indexes:
    "response_pkey" PRIMARY KEY, btree (response_id)
Foreign-key constraints:
    "response_deployed_url_id_fkey" FOREIGN KEY (deployed_url_id) REFERENCES deployed_url(deployed_url_id)
    "response_option_id_fkey" FOREIGN KEY (option_id) REFERENCES option(option_id)
    "response_question_id_fkey" FOREIGN KEY (question_id) REFERENCES question(question_id)
    "response_survey_info_id_fkey" FOREIGN KEY (survey_info_id) REFERENCES survey_info(survey_info_id)

```

**Comment by ryantanaka** [comment]
@carlosparadis, thanks for reviewing this! I've pull the changes onto the server and tested them out. Everything seems to be working fine. Will test it a bit more before I close this issue. 

As for the concern about sql injection type issues, I'm not too worried about this for several reasons. 
First I followed the examples in the psycopg2 docs regarding how to correctly pass parameters to the queries (http://initd.org/psycopg/docs/usage.html#passing-parameters-to-sql-queries). Second, When users click on the buttons, the underlying elm code doesn't look at any of the html content in the button. It just uses whatever data was pulled from the database prior to generate the buttons and then send responses back. So there is no place (that i know of ) where a user can "inject" something dangerous. 

I also need to tell scrape-util to stop looking for survey_display data since we handle that on our own now.

**Comment by carlosparadis** [comment]
Got it, we should be safe than on the SQL side.

> I also need to tell scrape-util to stop looking for survey_display data since we handle that on our own now.

Good reminder, I totally overlooked this. Make sure to hyperlink this issue to it! :)

**Comment by carlosparadis** [comment]
@ryantanaka Did you have a chance to test it out? :D I want to close this.

**Comment by ryantanaka** [comment]
@carlosparadis , yup closing this now!
