### ISSUE TITLE
Adding Emoji UTF-8 code to existing questions changes order of questions

### ISSUE THREAD

**Issue by carlosparadis** [erdl/survey_display#6]
This is a strange behavior and was reported during the implementation of issue #5. 

@ryantanaka What was edited in the database by you and Eileen?

**Comment by ryantanaka** [comment]
@carlosviansi 

> What was edited in the database by you and Eileen?

We edited the following rows in kiosk.options by adding the utf-8 emojis:
- (1, 1, Highly acceptable, 3)
- (56, 11, Highly acceptable, 3)
- (42, 8, Highly acceptable, 3)

It seems as though the edit of these threw their "current ordering" off in the database, therefore causing the query (which has no `ORDER BY` type clause) to return data that is not in the order we want it to be. Consequently, the buttons are rendered out of order on the screen. 

I did a quick test to confirm this. The `active` variable in psql.[load_active()](https://github.com/erdl/survey_display/blob/e5c27832d874af064d110d934be9a9d56e5e3c23/occquse/utils/psql.py#L45) contains dictionaries of dictionaries of dictionaries of lists which hold the responses for the test1kiosk survey's available responses. I sorted these responses based on key and the browser then rendered the buttons in the correct order. 

```
active['test1kiosk']['survey']['itms'][0]['opts'] = sorted(active['test1kiosk']['survey']['itms'][0]['opts'], key=lambda k: k['code'])
```
^  as the code above illustrates, I had to dig down pretty far to get to the data we needed so as you suggested, I'll work on adding in a `ORDER` type column in the options table of my local database so that we aren't relying on the database just happening to be in order for correctness

**Comment by carlosparadis** [comment]
@ryantanaka Make sure you stay consistent in the nomenclature in the database. In the `survey_question` table, the column name is `question_position`. As such, to stay consistent, you should call in the appropriate table `response_position`. 

Perhaps later we can modify both to order, but let's stick calling things with the same purpose with the same name format.

Also, there is one more thing I want you to do.

## Branching

1. Make sure the code you are editing is a git clone of your **fork**, not of the **project in erdl*. 
2. Before you start modifying the code (if you already did, git clone again other folder and do this and the next steps), please create a branch: 
   2.1 `git checkout -b 6-fix-response-order` will create a new branch from your master branch. **Make sure you did no modifications to the code as compared to `erdl/master`. If you did, better do another fork and git clone a new fork to be sure. 
  2.2 If you type `git branch` you should see you are now in the `6-fix-response-order` branch. Your folder in your computer will be associated to it. You can `git checkout master` to go back to branch master, in which your changes go back to master (including in your folder from the GUI), and you can type again `git checkout 6-fix-response-order` to switch back to your working branch. 

From here and onwards you do pretty much the same stuff as you would do in master. 

Keep all the fixes to `1 commit` so we don't pollute `erdl/master` with intermediate commits (and remember to mention the commit #6 at the start of the message). 

Once you are ready, from your `6-fix-response-order` type: (you can know which branch you are when you type `git branch`, here is an * beside the active one):

`git push origin 6-fix-response-order`. 

This will push the new branch to your remote fork on github. Then, initate the Pull Request, via your browser by clicking "New Pull Request". 

The most important thing is that you do the new branch from your fork master branch, and make sure your fork master branch is the most current version of the project. 

We should get you started with branches after all, I think this will be a good exercise. Don't forget there is a lecture about branches on Udacity Git course, you may want to brush if this doesn't make sense :-) If I typoed any command or you get some funky error let me know.

**Comment by ryantanaka** [comment]
Sorry made the mistake of accidentally pushing my branch straight to erdl/survey_display ... You can delete that branch, and a proper pull request was submitted from my fork of the repository.

**Comment by carlosparadis** [comment]
Exercising the principle of least permissions for tasks to get done never fails it seems haha. I deleted the branch :-)
